### ISSUE TITLE
Can't install abb via command prompt

### ISSUE THREAD

**Issue by gmanvel** [mspnp/template-building-blocks#432] opened 2020-08-06 08:18 UTC
Trying to install abb from command line fails with 

> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mspnp%2fazure-building-blocks - Not found

error message.

### Steps to reproduce:

Just run following command (documented in [wiki page](https://github.com/mspnp/template-building-blocks/wiki)) from command prompt

`npm install -g @mspnp/azure-building-blocks`

fails with error message

> npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mspnp%2fazure-building-blocks - Not found
npm ERR! 404
npm ERR! 404  '@mspnp/azure-building-blocks@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Complete log of the run
> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@mspnp/azure-building-blocks' ]
2 info using npm@6.11.3
3 info using node@v10.16.3
4 verbose npm-session 550190c4b494e0a2
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@mspnp%2fazure-building-blocks 13911ms
8 http fetch GET 404 https://registry.npmjs.org/@mspnp%2fazure-building-blocks 13829ms
9 silly fetchPackageMetaData error for @mspnp/azure-building-blocks@latest 404 Not Found - GET https://registry.npmjs.org/@mspnp%2fazure-building-blocks - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 27774ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@mspnp%2fazure-building-blocks - Not found
12 verbose stack     at res.buffer.catch.then.body (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid @mspnp/azure-building-blocks@latest
15 verbose cwd C:\Users\admin
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@mspnp/azure-building-blocks"
18 verbose node v10.16.3
19 verbose npm  v6.11.3
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@mspnp%2fazure-building-blocks - Not found
22 error 404
23 error 404 '@mspnp/azure-building-blocks@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by hallihan** [comment] 2020-10-02 14:19
This seems to be working for me.  Can you try visiting the URL <https://registry.npmjs.org/@mspnp%2fazure-building-blocks> from a web browser, or do `curl https://registry.npmjs.org/@mspnp%2fazure-building-blocks` from your command line and see if you get back the package definition JSON?

If you are still getting a 404, you can try `curl -vI https://registry.npmjs.org/@mspnp%2fazure-building-blocks` - unless something is redirecting registry.npmjs.org in your environment, you should see details pointing to the Cloudflare CDN servers that are used for registry.npmjs.org.

**Comment by hallihan** [comment] 2020-12-21 19:37
Can not reproduce error, closing issue.

**Closed by hallihan** 2020-12-21 19:37 UTC
