### ISSUE TITLE
Editing bash file in Azure Shell not persistant

### ISSUE THREAD

**Issue by pkbullock** [mspnp/template-building-blocks#362] opened 2018-01-04 06:46 UTC
Hi

After following the article: https://github.com/mspnp/template-building-blocks/wiki/Install-Azure-Building-Blocks-in-Azure-Cloud-Shell 

I have installed another Microsoft PnP npm package called OfficeCLI however, editing the bash file in this article is not persistent. Is there an alternative way to persist the export path across shell sessions?

Thanks
Paul Bullock

**Comment by telmosampaio** [comment] 2018-02-13 00:52
The change should persist. Unless you deleted your storage account that was used to persist changes to the shell, and started a new shell. That creates a new storage account for changes, and you lose all changes previously persisted.

**Comment by pkbullock** [comment] 2018-02-13 06:54
Hi @telmosampaio 

Thanks, I have looked into this more specifically, its step 4, 

Add the following line to the end of the ~/.bashrc file:
export PATH="$HOME/.npm-global/bin:$PATH"

Editing the bachrc file doesn't always persists between shell sessions or if you leave it for a day or so. Difficult to reproduce exact steps but easy to occur.

I feel this could be a limitation of using Azure Shell in this way. 

Paul

**Comment by woodp** [comment] 2018-09-11 17:45
Hi @pkbullock I'm afraid I was not able to reproduce the problem.
Here you have updated info on this that might help: https://docs.microsoft.com/en-us/azure/cloud-shell/persisting-shell-storage

**Comment by woodp** [comment] 2018-09-18 17:39
closing this, reopen if you have any issues

**Closed by woodp** 2018-09-18 17:39 UTC
